variables:
  SONAR_TOKEN: "6b45dcc94c7115748444f93850c3a50709f72ed6"
  SONAR_HOST_URL: "https://sonar.iconext.cc"
  # config by project
  SONAR_PROJECT_NAME: "NuGet-Zero"
  SONAR_PROJECT_KEY: "com.iconext:zero"
  SONAR_PROJECT_VERSION: "1.0-SNAPSHOT"
  SRC_FOLDER: ".NET Standard"
  SOLUTION_FILE: "ModuleZero.Standard.sln"

sonar:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim-amd64
  before_script:
    # The end step requires Java
    - export PATH="$PATH:/jdk/bin"
    - java --version
    # install sonarscanner
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install --global dotnet-sonarscanner
    # restore submodule
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - cd "$SRC_FOLDER"
    - dotnet restore $SOLUTION_FILE --packages /cache/packages
    - dotnet sonarscanner begin /k:"$SONAR_PROJECT_KEY" /name:"$SONAR_PROJECT_NAME" /version:"$SONAR_PROJECT_VERSION" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN" 
    - dotnet build $SOLUTION_FILE --configuration Release
    - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
  only:
    - master-5.0
  tags:
    - public-dotnetcore